- name: nginxpalbook
  hosts: webservers
  become: true

  tasks:
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: latest
    
    - name: setup docker
      ansible.builtin.service:
        name:  docker
        state: started
    
    - name: add user to docker group
      ansible.builtin.shell:
        cmd: sudo usermod -aG docker ec2-user
      args:
        executable: /bin/bash
      ignore_errors: true
    
    # - name: refresh the docker group
    #   ansible.builtin.shell: sudo -u $USER newgrp docker
    #   args:
    #     executable: /bin/bash
    #   ignore_errors: true 
    
    - name: enable at boot and restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: docker pull & run
      ansible.builtin.shell: |
        docker rmi adelekegbolahan/nginx-image --force
        docker pull adelekegbolahan/nginx-image:latest
        docker rm nginx_container --force
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: run application container
      ansible.builtin.shell: |
        docker run -dit --name nginx_container -p 7000:8000 -p 443:443 adelekegbolahan/nginx-image:latest